apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhtap-prototype
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-prototype
    app.kubernetes.io/part-of: rhtap-prototype
  name: rhtap-prototype
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rhtap-prototype
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rhtap-prototype
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhel-bootc-tenant/rhtap-prototype/rhtap-prototype@sha256:c2debf16ada95090ff64c7ed2ca9069cadc3ce6e66aed0ddcdc7a72948d16bb3
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
