apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhtap-prototype
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-prototype
    app.kubernetes.io/part-of: rhtap-prototype
  name: rhtap-prototype
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rhtap-prototype
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rhtap-prototype
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhel-bootc-tenant/rhtap-prototype/rhtap-prototype@sha256:a3ab201bc4e6dd62e92b13736a1b6884b0cfa0bb3d714180ca9e255e62928557
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
