apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhtap-prototype
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-prototype
    app.kubernetes.io/part-of: rhtap-prototype
  name: rhtap-prototype
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rhtap-prototype
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rhtap-prototype
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhel-bootc-tenant/rhtap-prototype/rhtap-prototype@sha256:939791b8f0e9f2c629d5bd267d95415873ca0e1675f51a046e771c3e43bc3a2b
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
