apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhtap-prototype
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhel-bootc-tenant/rhtap-prototype/rhtap-prototype@sha256:a3ab201bc4e6dd62e92b13736a1b6884b0cfa0bb3d714180ca9e255e62928557
        name: container-image
        resources: {}
status: {}
